import type { Metadata } from 'next';
import './globals.css';
import { Kaushan_Script, Montserrat } from 'next/font/google';

const kaushan = Kaushan_Script({
    subsets: ['latin'],
    weight: ['400'],
    variable: '--logo-font',
});

const montserrat = Montserrat({
    subsets: ['latin'],
    variable: '--body-font',
});

export const metadata: Metadata = {
    title: 'Harsh Kumar',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`antialiased font-body ${montserrat.variable} ${kaushan.variable}`}
            >
                {children}
            </body>
        </html>
    );
}
